version: "3.8"

services:
  db:
    container_name: wordpress_db
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_pasdw
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: your_password
    networks:
      - network

  wordpress:
    depends_on:
      - db
    container_name: wordpress_app
    image: wordpress:fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: your_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wp_data:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - network

  nginx:
    container_name: wordpress_webserver
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - network

volumes:
  db_data:
  wp_data:

networks:
  network:
